version: '3.1'
services:
  db:
    image: mysql:8
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa
    ports: 
      - "3306:3306"
    networks:
      - my-music-api-network

  my-music-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: lucas/my-music-api
    container_name: my-music-api-container
    ports:
      - "8081:8081"
    networks:
      - my-music-api-network
    environment: 
        WAIT_HOSTS: mysql:3306 
    depends_on: 
        - "db"

networks:
  my-music-api-network:
    driver: bridge